@api = http://localhost:3000/tasks

GET {{api}}

###
GET {{api}}/5

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
    "title": "I must create an app",
    "description": "using node"
}
###
DELETE {{api}}/1

### 
PUT  {{api}}/13
Content-Type: application/json

{
    "title": "aaaaaaaaaaaaaaaaaaaaa",
    "description": "hola como estai"
    
}